base:
  apiGateway: http://service.api-gateway
  redis:
    host: redis
    port: 8000
service.registry.schedule:
  scheduleExpiry: 6
  activeCarriers:
    CMDU: false
    ANNU: true
    CHNL: true
    APLU: true
    ZIMU: true
    HLCU: true
    MSCU: true
    OOLU: true
    COSU: true
    ONEY: true
    MAEU: true
    MAEI: true